### ISSUE TITLE
Unprocessed ie-hex-str() Sass directives in flame.css

### ISSUE THREAD

**Issue by jeromecaffaro** [flamejs/flame-starter-kit#1]
The current flame.css file of the starter kit (http://github.com/flamejs/flame-starter-kit/blob/e840ba774b/css/flame.css) refers to 'ie-hex-str()' function (within the CSS declarations for the gradients),  leading to some blue-ish result of the web app when viewed with Internet Explorer. 

The calls to the 'ie-hex-str()' function should have been replaced by Sass when processing flame.css.scss (provided that  the master branch of Sass is used, since  'ie-hex-str()'  does seem supported with the currently released version (3.1.19) of Sass).

The same applies to the demo address book app http://github.com/flamejs/flame-address-book

**Comment by ctimmerm** [comment]
Yeah, the `ie-hex-str` function isn't available during the build process it seems, I'll have a look at it and update the starter kit.

**Comment by ctimmerm** [comment]
This has been fixed in https://github.com/flamejs/flame.js/commit/79f90fe40651c6663fdae78e9d7b6c69b1338ddb
I'll update the starter kit when I'll tag a new Flame version (soon).
